### ISSUE TITLE
TypeError: Cannot read property 'precision' of undefined

### ISSUE THREAD

**Issue by imanoracle** [jpeg-js/jpeg-js#80] opened 2020-10-17 14:35 UTC
Hi,

I got the following error with the provided input:

```
input:/Users/cydarien/Documents/test/jpeg/node_modules/jpeg-js/lib/decoder.js:95
    var precision = frame.precision;
                          ^

TypeError: Cannot read property 'precision' of undefined
    at decodeScan (/Users/cydarien/Documents/test/jpeg/node_modules/jpeg-js/lib/decoder.js:95:27)
    at constructor.parse (/Users/cydarien/Documents/test/jpeg/node_modules/jpeg-js/lib/decoder.js:744:29)
    at Object.decode (/Users/cydarien/Documents/test/jpeg/node_modules/jpeg-js/lib/decoder.js:1004:11)
    at Object.<anonymous> (/Users/cydarien/Documents/test/jpeg/test.js:5:6)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
Code:
```
const jpeg = require('jpeg-js');
var fs = require('fs');

var buf = fs.readFileSync('crash');
jpeg.decode(buf);

```
[crash.zip](https://github.com/eugeneware/jpeg-js/files/5395853/crash.zip)

**Comment by donmahallem** [comment] 2021-01-27 10:08
This is probably a duplicate/related to #63

**Comment by patrickhulce** [comment] 2021-07-15 20:03
Indeed dupe of #63

**Closed by patrickhulce** 2021-07-15 20:03 UTC
Labels: bug, needs-investigation
